name = "The-InBetween"
author = "Conquerix"
version = "v0.10.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80d3160eda95b6543b3392d436b62e2ef1a27b2eb62e2b736175417ec7bc297b"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
