name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a956eeb5857c33c7b66e32d6614882577f89fd746efc0cf1f3d0d76ac08b29a"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
