name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b252200f4e637a2984b2e6652609b2c4159ec713f44279ced20bfbd2614aac7"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
