name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ae8ece76a8f004c3f6cab7d535f3cb4b473f71759d43dbf48432e99012307fc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
