name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dead69a322d57f5b77d89842b5caee490ac0bfb0230434c3dc3fa6a9d185b83f"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
