name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "814f3bfe1c81d34d976693fbd5ac70d6b57227e6d194462ee4c837aa0d07630f"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
