name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28c9a481b363eba90330588e1e3c33c8df488a96e1a09e7f099be2078374b6f1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
