name = "The-InBetween"
author = "Conquerix"
version = "v0.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4856e21ee43c338e40d89bc04060a69cea84992acca02ff03ef5c32532a86bfb"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
