name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9625b1591b1186fc5dc786df17cf542633b0d79383d8ebaca6e539a88bfcf3"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
