name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c27afb99777b5d859d356c70e491a532b63a2092b52dc645e04129f54d1412f0"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
