name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93d1f6f911412ae8bc94ad761bf0bd8a778c28d8000b17526e8075b8d024634e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
