name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d5a644dd027de6a9335268b27c279b0a3e5a7cdb3078fda7323d1222d1275f1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
