name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d045b827416cd70c1b05451994518ca5281a3077d780bfe56350fd2989b1204"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
