name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bba2426604ea9bcfab478f8b0e4b507963ad9f73ecdbe5ca3186709aec8d6a2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
