name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fccebe9d17975d49f9163ce69d717fc3337000be669ec0de8c70cb534d7c3ff7"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
