name = "The-InBetween"
author = "Conquerix"
version = "v0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e70e894fbec490efbbfab13b9f2be9cbcc7bdbbff582d4ca62fce49b34a8fa03"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
