name = "The-InBetween"
author = "Conquerix"
version = "v0.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f030ac011d79239c8c23048ba08cd2f61249d5dad01ce9c979e7f0e413f2f4e8"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
